Angle-MVC6-jQuery/src/Angle-MVC6-jQuery/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Angle_MVC6_jQuery.Controllers
{
    public class PagesController : Controller
    {
        public IActionResult Error_404()
        {
            return View();
        }
        public IActionResult Lock() {
            return View();
        }
        public IActionResult Login() {
            return View();
        }
        public IActionResult Recover() {
            return View();
        }
        public IActionResult Register() {
            return View();
        }
        public IActionResult Template()
        {
            return View();
        }
        public ActionResult Maintenance()
        {
            return View();
        }
        public ActionResult Error_500()
        {
            return View();
        }
    }
}

Angle-MVC6-jQuery/src/Angle-MVC6-jQuery/Views/Shared/_Footer.cshtml
<span>&copy; 2015 - Angle</span>

Angle-MVC6-jQuery/src/Angle-MVC6-jQuery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Bootstrap Admin App + jQuery">
    <meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
    <title>@ViewData["Title"] - Bootstrap Admin Template</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Place styles for plugins -->
    @if (IsSectionDefined("Styles"))
        {@RenderSection("Styles", required: false)}

    <environment names="Development">
        <!-- =============== VENDOR STYLES ===============-->
        <link href="~/lib/fontawesome/css/font-awesome.css" rel="stylesheet" />
        <link href="~/lib/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" />
        <link href="~/lib/animate.css/animate.css" rel="stylesheet" />
        <link href="~/lib/whirl/dist/whirl.css" rel="stylesheet" />
        <!-- =============== BOOTSTRAP STYLES ===============-->
        <link href="~/css/bootstrap.css" rel="stylesheet" />
        <!-- =============== APP STYLES ===============-->
        <link href="~/css/app.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <!-- =============== VENDOR STYLES ===============-->
        <link href="~/lib/fontawesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/lib/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" />
        <link href="~/lib/animate.css/animate.min.css" rel="stylesheet" />
        <link href="~/lib/whirl/dist/whirl.css" rel="stylesheet" />
        <!-- =============== BOOTSTRAP STYLES ===============-->
        <link href="~/css/bootstrap.css" rel="stylesheet" />
        <!-- =============== APP STYLES ===============-->
        <link href="~/css/app.css" rel="stylesheet" asp-append-version="true" />
    </environment>


</head>
<body>
    <div class="wrapper">
        <!-- top navbar-->
        <header class="topnavbar-wrapper">
            @Html.Partial("_TopNavbar")
        </header>
        <!-- sidebar-->
        <aside class="aside">
            @Html.Partial("_Sidebar")
        </aside>
        <!-- offsidebar-->
        <aside class="offsidebar hide">
            @Html.Partial("_Offsidebar")
        </aside>
        <!-- Main section-->
        <section>
            <!-- Page content-->
            <div class="content-wrapper">
                @RenderBody()
            </div>
        </section>
        <!-- Page footer-->
        <footer>
            @Html.Partial("_Footer")
        </footer>
    </div>

    @if (IsSectionDefined("BodyArea")) {
        @RenderSection("BodyArea", required: false)
    }

    <environment names="Development">

        <!-- =============== VENDOR SCRIPTS ===============-->

        <script src="~/lib/modernizr/modernizr.custom.js"></script>
        <script src="~/lib/matchMedia/matchMedia.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jQuery-Storage-API/jquery.storageapi.js"></script>
        <script src="~/lib/jquery.easing/js/jquery.easing.js"></script>
        <script src="~/lib/animo.js/animo.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.js"></script>
        <script src="~/lib/screenfull/dist/screenfull.js"></script>
        <script src="~/lib/jquery-localize-i18n/dist/jquery.localize.js"></script>

        <!-- =============== PAGE VENDOR SCRIPTS ===============-->
        @RenderSection("scripts", required: false)

        <!-- =============== APP SCRIPTS ===============-->

        <!-- App init -->
        <script src="~/master/js/app.init.js"></script>
        <!-- Modules -->
        <script src="~/master/js/modules/bootstrap-start.js"></script>
        <script src="~/master/js/modules/calendar.js"></script>
        <script src="~/master/js/modules/classyloader.js"></script>
        <script src="~/master/js/modules/clear-storage.js"></script>
        <script src="~/master/js/modules/constants.js"></script>
        <script src="~/master/js/modules/flatdoc.js"></script>
        <script src="~/master/js/modules/fullscreen.js"></script>
        <script src="~/master/js/modules/gmap.js"></script>
        <script src="~/master/js/modules/load-css.js"></script>
        <script src="~/master/js/modules/localize.js"></script>
        <script src="~/master/js/modules/maps-vector.js"></script>
        <script src="~/master/js/modules/navbar-search.js"></script>
        <script src="~/master/js/modules/notify.js"></script>
        <script src="~/master/js/modules/now.js"></script>
        <script src="~/master/js/modules/panel-tools.js"></script>
        <script src="~/master/js/modules/play-animation.js"></script>
        <script src="~/master/js/modules/porlets.js"></script>
        <script src="~/master/js/modules/sidebar.js"></script>
        <script src="~/master/js/modules/skycons.js"></script>
        <script src="~/master/js/modules/slimscroll.js"></script>
        <script src="~/master/js/modules/sparkline.js"></script>
        <script src="~/master/js/modules/table-checkall.js"></script>
        <script src="~/master/js/modules/toggle-state.js"></script>
        <script src="~/master/js/modules/utils.js"></script>
        <script src="~/master/js/modules/chart.js"></script>
        <script src="~/master/js/modules/morris.js"></script>
        <script src="~/master/js/modules/rickshaw.js"></script>
        <script src="~/master/js/modules/chartist.js"></script>
        <script src="~/master/js/modules/tour.js"></script>
        <script src="~/master/js/modules/sweetalert.js"></script>
        <script src="~/master/js/modules/color-picker.js"></script>
        <script src="~/master/js/modules/imagecrop.js"></script>
        <script src="~/master/js/modules/chart-knob.js"></script>
        <script src="~/master/js/modules/chart-easypie.js"></script>
        <script src="~/master/js/modules/select2.js"></script>
        <!-- Demos -->
        <script src="~/master/js/modules/demo/demo-datatable.js"></script>
        <script src="~/master/js/modules/demo/demo-flot.js"></script>
        <script src="~/master/js/modules/demo/demo-forms.js"></script>
        <script src="~/master/js/modules/demo/demo-panels.js"></script>
        <script src="~/master/js/modules/demo/demo-search.js"></script>
        <script src="~/master/js/modules/demo/demo-vector-map.js"></script>
        <script src="~/master/js/modules/demo/demo-jqgrid.js"></script>
        <script src="~/master/js/modules/demo/demo-sortable.js"></script>
        <script src="~/master/js/modules/demo/demo-nestable.js"></script>
        <script src="~/master/js/modules/demo/demo-upload.js"></script>
        <script src="~/master/js/modules/demo/demo-wizard.js"></script>
        <script src="~/master/js/modules/demo/demo-xeditable.js"></script>
        <script src="~/master/js/modules/demo/demo-jqcloud.js"></script>
        <script src="~/master/js/modules/demo/demo-rtl.js"></script>
        <!-- Custom -->
        <script src="~/master/js/custom/custom.js"></script>

    </environment>

    <environment names="Staging,Production">

        <!-- =============== VENDOR SCRIPTS ===============-->

        <script src="~/lib/modernizr/modernizr.custom.js"></script>
        <script src="~/lib/matchMedia/matchMedia.js"></script>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/lib/jQuery-Storage-API/jquery.storageapi.min.js"></script>
        <script src="~/lib/jquery.easing/js/jquery.easing.min.js"></script>
        <script src="~/lib/animo.js/animo.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.min.js"></script>
        <script src="~/lib/screenfull/dist/screenfull.js"></script>
        <script src="~/lib/jquery-localize-i18n/dist/jquery.localize.min.js"></script>

        <!-- =============== PAGE VENDOR SCRIPTS ===============-->
        @RenderSection("scripts", required: false)

        <!-- =============== APP SCRIPTS ===============-->

        <script src="~/js/app.js"></script>

    </environment>
    


</body>
</html>

Angle-MVC6-jQuery/src/Angle-MVC6-jQuery/Views/Shared/_LayoutHorizontal.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Bootstrap Admin App + jQuery">
    <meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
    <title>@ViewData["Title"] - Bootstrap Admin Template</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Place styles for plugins -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    <environment names="Development">
        <!-- =============== VENDOR STYLES ===============-->
        <link href="~/lib/fontawesome/css/font-awesome.css" rel="stylesheet" />
        <link href="~/lib/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" />
        <link href="~/lib/animate.css/animate.css" rel="stylesheet" />
        <link href="~/lib/whirl/dist/whirl.css" rel="stylesheet" />
        <!-- =============== BOOTSTRAP STYLES ===============-->
        <link href="~/css/bootstrap.css" rel="stylesheet" />
        <!-- =============== APP STYLES ===============-->
        <link href="~/css/app.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <!-- =============== VENDOR STYLES ===============-->
        <link href="~/lib/fontawesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/lib/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" />
        <link href="~/lib/animate.css/animate.min.css" rel="stylesheet" />
        <link href="~/lib/whirl/dist/whirl.css" rel="stylesheet" />
        <!-- =============== BOOTSTRAP STYLES ===============-->
        <link href="~/css/bootstrap.css" rel="stylesheet" />
        <!-- =============== APP STYLES ===============-->
        <link href="~/css/app.css" rel="stylesheet" asp-append-version="true" />
    </environment>


</head>
<body class="layout-h">
    <div class="wrapper">
        <!-- top navbar-->
        <header class="topnavbar-wrapper">
            @Html.Partial("_TopNavbarHorizontal")
        </header>
        <!-- offsidebar-->
        <aside class="offsidebar hide">
            @Html.Partial("_Offsidebar")
        </aside>
        <!-- Main section-->
        <section>
            <!-- Page content-->
            <div class="content-wrapper">
                @RenderBody()
            </div>
        </section>
        <!-- Page footer-->
        <footer>
            @Html.Partial("_Footer")
        </footer>
    </div>

    @if (IsSectionDefined("BodyArea"))
    {
        @RenderSection("BodyArea", required: false)
    }

    <environment names="Development">

        <!-- =============== VENDOR SCRIPTS ===============-->

        <script src="~/lib/modernizr/modernizr.custom.js"></script>
        <script src="~/lib/matchMedia/matchMedia.js"></script>
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jQuery-Storage-API/jquery.storageapi.js"></script>
        <script src="~/lib/jquery.easing/js/jquery.easing.js"></script>
        <script src="~/lib/animo.js/animo.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.js"></script>
        <script src="~/lib/screenfull/dist/screenfull.js"></script>
        <script src="~/lib/jquery-localize-i18n/dist/jquery.localize.js"></script>

        <!-- =============== APP SCRIPTS ===============-->
        <!-- App init -->
        <script src="~/master/js/app.init.js"></script>
        <!-- Modules -->
        <script src="~/master/js/modules/bootstrap-start.js"></script>
        <script src="~/master/js/modules/calendar.js"></script>
        <script src="~/master/js/modules/classyloader.js"></script>
        <script src="~/master/js/modules/clear-storage.js"></script>
        <script src="~/master/js/modules/constants.js"></script>
        <script src="~/master/js/modules/flatdoc.js"></script>
        <script src="~/master/js/modules/fullscreen.js"></script>
        <script src="~/master/js/modules/gmap.js"></script>
        <script src="~/master/js/modules/load-css.js"></script>
        <script src="~/master/js/modules/localize.js"></script>
        <script src="~/master/js/modules/maps-vector.js"></script>
        <script src="~/master/js/modules/navbar-search.js"></script>
        <script src="~/master/js/modules/notify.js"></script>
        <script src="~/master/js/modules/now.js"></script>
        <script src="~/master/js/modules/panel-tools.js"></script>
        <script src="~/master/js/modules/play-animation.js"></script>
        <script src="~/master/js/modules/porlets.js"></script>
        <script src="~/master/js/modules/sidebar.js"></script>
        <script src="~/master/js/modules/skycons.js"></script>
        <script src="~/master/js/modules/slimscroll.js"></script>
        <script src="~/master/js/modules/sparkline.js"></script>
        <script src="~/master/js/modules/table-checkall.js"></script>
        <script src="~/master/js/modules/toggle-state.js"></script>
        <script src="~/master/js/modules/utils.js"></script>
        <script src="~/master/js/modules/chart.js"></script>
        <script src="~/master/js/modules/morris.js"></script>
        <script src="~/master/js/modules/rickshaw.js"></script>
        <script src="~/master/js/modules/chartist.js"></script>
        <script src="~/master/js/modules/tour.js"></script>
        <script src="~/master/js/modules/sweetalert.js"></script>
        <script src="~/master/js/modules/color-picker.js"></script>
        <script src="~/master/js/modules/imagecrop.js"></script>
        <script src="~/master/js/modules/chart-knob.js"></script>
        <script src="~/master/js/modules/chart-easypie.js"></script>
        <script src="~/master/js/modules/select2.js"></script>
        <!-- Demos -->
        <script src="~/master/js/modules/demo/demo-datatable.js"></script>
        <script src="~/master/js/modules/demo/demo-flot.js"></script>
        <script src="~/master/js/modules/demo/demo-forms.js"></script>
        <script src="~/master/js/modules/demo/demo-panels.js"></script>
        <script src="~/master/js/modules/demo/demo-search.js"></script>
        <script src="~/master/js/modules/demo/demo-vector-map.js"></script>
        <script src="~/master/js/modules/demo/demo-jqgrid.js"></script>
        <script src="~/master/js/modules/demo/demo-sortable.js"></script>
        <script src="~/master/js/modules/demo/demo-nestable.js"></script>
        <script src="~/master/js/modules/demo/demo-upload.js"></script>
        <script src="~/master/js/modules/demo/demo-wizard.js"></script>
        <script src="~/master/js/modules/demo/demo-xeditable.js"></script>
        <script src="~/master/js/modules/demo/demo-jqcloud.js"></script>
        <script src="~/master/js/modules/demo/demo-rtl.js"></script>
        <!-- Custom -->
        <script src="~/master/js/custom/custom.js"></script>

    </environment>

    <environment names="Staging,Production">

        <!-- =============== VENDOR SCRIPTS ===============-->

        <script src="~/lib/modernizr/modernizr.custom.js"></script>
        <script src="~/lib/matchMedia/matchMedia.js"></script>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/lib/jQuery-Storage-API/jquery.storageapi.min.js"></script>
        <script src="~/lib/jquery.easing/js/jquery.easing.min.js"></script>
        <script src="~/lib/animo.js/animo.js"></script>
        <script src="~/lib/slimScroll/jquery.slimscroll.min.js"></script>
        <script src="~/lib/screenfull/dist/screenfull.js"></script>
        <script src="~/lib/jquery-localize-i18n/dist/jquery.localize.min.js"></script>

        <!-- =============== APP SCRIPTS ===============-->

        <script src="~/js/app.js"></script>

    </environment>

    <!-- =============== PAGE VENDOR SCRIPTS ===============-->
    @RenderSection("scripts", required: false)

</body>
</html>

Angle-MVC6-jQuery/src/Angle-MVC6-jQuery/Views/Shared/_TopNavbar.cshtml
<!-- START Top Navbar-->
<nav class="navbar topnavbar">
   <!-- START navbar header-->
   <div class="navbar-header">
      <a href="#/" class="navbar-brand">
         <div class="brand-logo">
            <img src="~/images/logo.png" alt="App Logo" class="img-responsive" />
         </div>
         <div class="brand-logo-collapsed">
             <img src="~/images/logo-single.png" alt="App Logo" class="img-responsive" />
         </div>
      </a>
   </div>
   <!-- END navbar header-->
   <!-- START Nav wrapper-->
   <div class="nav-wrapper">
      <!-- START Left navbar-->
      <ul class="nav navbar-nav">
         <li>
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <a href="#" data-toggle-state="aside-collapsed" class="hidden-xs">
               <em class="fa fa-navicon"></em>
            </a>
            <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
            <a href="#" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
               <em class="fa fa-navicon"></em>
            </a>
         </li>
         <!-- START User avatar toggle-->
         <li>
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
             <a id="user-block-toggle" href="#user-block" data-toggle="collapse">
                 <em class="icon-user"></em>
             </a>
         </li>
         <!-- END User avatar toggle-->
         <!-- START lock screen-->
         <li>
             <a href="@Url.Action("Lock", "Pages")" title="Lock screen">
                 <em class="icon-lock"></em>
             </a>
         </li>
         <!-- END lock screen-->
      </ul>
      <!-- END Left navbar-->
      <!-- START Right Navbar-->
      <ul class="nav navbar-nav navbar-right">
         <!-- Search icon-->
         <li>
            <a href="#" data-search-open="">
               <em class="icon-magnifier"></em>
            </a>
         </li>
         <!-- Fullscreen (only desktops)-->
         <li class="visible-lg">
            <a href="#" data-toggle-fullscreen="">
               <em class="fa fa-expand"></em>
            </a>
         </li>
         <!-- START Alert menu-->
         <li class="dropdown dropdown-list">
            <a href="#" data-toggle="dropdown">
               <em class="icon-bell"></em>
               <div class="label label-danger">11</div>
            </a>
            <!-- START Dropdown menu-->
            <ul class="dropdown-menu animated flipInX">
               <li>
                  <!-- START list group-->
                  <div class="list-group">
                     <!-- list item-->
                     <a href="#" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-twitter fa-2x text-info"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0">New followers</p>
                              <p class="m0 text-muted">
                                 <small>1 new follower</small>
                              </p>
                           </div>
                        </div>
                     </a>
                     <!-- list item-->
                     <a href="#" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-envelope fa-2x text-warning"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0">New e-mails</p>
                              <p class="m0 text-muted">
                                 <small>You have 10 new emails</small>
                              </p>
                           </div>
                        </div>
                     </a>
                     <!-- list item-->
                     <a href="#" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-tasks fa-2x text-success"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0">Pending Tasks</p>
                              <p class="m0 text-muted">
                                 <small>11 pending task</small>
                              </p>
                           </div>
                        </div>
                     </a>
                     <!-- last list item -->
                     <a href="#" class="list-group-item">
                        <small>More notifications</small>
                        <span class="label label-danger pull-right">14</span>
                     </a>
                  </div>
                  <!-- END list group-->
               </li>
            </ul>
            <!-- END Dropdown menu-->
         </li>
         <!-- END Alert menu-->
         <!-- START Contacts button-->
         <li>
            <a href="#" data-toggle-state="offsidebar-open" data-no-persist="true">
               <em class="icon-notebook"></em>
            </a>
         </li>
         <!-- END Contacts menu-->
      </ul>
      <!-- END Right Navbar-->
   </div>
   <!-- END Nav wrapper-->
   <!-- START Search form-->
   <form role="search" action="search.html" class="navbar-form">
      <div class="form-group has-feedback">
         <input type="text" placeholder="Type and hit enter ..." class="form-control" />
         <div data-search-dismiss="" class="fa fa-times form-control-feedback"></div>
      </div>
      <button type="submit" class="hidden btn btn-default">Submit</button>
   </form>
   <!-- END Search form-->
</nav>
<!-- END Top Navbar-->

Angle-MVC6-jQuery/src/Angle-MVC6-jQuery/Views/Shared/_TopNavbarHorizontal.cshtml
<!-- START Top Navbar-->
<nav class="navbar topnavbar">
    <!-- START navbar header-->
    <div class="navbar-header">
        <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="#/" class="navbar-brand">
            <div class="brand-logo">
                <img src="~/images/logo.png" alt="App Logo" class="img-responsive" />
            </div>
            <div class="brand-logo-collapsed">
                <img src="~/images/logo-single.png" alt="App Logo" class="img-responsive" />
            </div>
        </a>
    </div>
    <!-- END navbar header-->
    <!-- START Nav wrapper-->
    <div class="navbar-collapse collapse">
        <!-- START Left navbar-->
        <ul class="nav navbar-nav">
            <li></li>
            <li class="@Html.isActive(controller: "Dashboard")">
                <a href="#dashboard" data-toggle="dropdown">Dashboard</a>
                <ul class="dropdown-menu animated fadeIn">
                    <li class="@Html.isActive("Dashboard", "Dashboard_v1")">
                        <a href="@Url.Action("Dashboard_v1", "Dashboard")">Dashboard v1</a>
                    </li>
                    <li class="@Html.isActive("Dashboard", "Dashboard_v2")">
                        <a href="@Url.Action("Dashboard_v2", "Dashboard")">Dashboard v2</a>
                    </li>
                    <li class="@Html.isActive("Dashboard", "Dashboard_v3")">
                        <a href="@Url.Action("Dashboard_v3", "Dashboard")">Dashboard v3</a>
                    </li>
                </ul>
            </li>
            <li class="@Html.isActive(controller: "Widgets")">
                <a href="@Url.Action("Index", "Widgets")">Widgets</a>
            </li>
        </ul>
        <!-- END Left navbar-->
        <!-- START Right Navbar-->
        <ul class="nav navbar-nav navbar-right">
            <!-- START lock screen-->
            <li>
                <a href="@Url.Action("Lock", "Pages")" title="Lock screen">
                    <em class="icon-lock"></em>
                </a>
            </li>
            <!-- END lock screen-->
            <!-- Search icon-->
            <li>
                <a href="#" data-search-open="">
                    <em class="icon-magnifier"></em>
                </a>
            </li>
            <!-- Fullscreen (only desktops)-->
            <li class="visible-lg">
                <a href="#" data-toggle-fullscreen="">
                    <em class="fa fa-expand"></em>
                </a>
            </li>
            <!-- START Alert menu-->
            <li class="dropdown dropdown-list">
                <a href="#" data-toggle="dropdown">
                    <em class="icon-bell"></em>
                    <div class="label label-danger">11</div>
                </a>
                <!-- START Dropdown menu-->
                <ul class="dropdown-menu animated flipInX">
                    <li>
                        <!-- START list group-->
                        <div class="list-group">
                            <!-- list item-->
                            <a href="#" class="list-group-item">
                                <div class="media-box">
                                    <div class="pull-left">
                                        <em class="fa fa-twitter fa-2x text-info"></em>
                                    </div>
                                    <div class="media-box-body clearfix">
                                        <p class="m0">New followers</p>
                                        <p class="m0 text-muted">
                                            <small>1 new follower</small>
                                        </p>
                                    </div>
                                </div>
                            </a>
                            <!-- list item-->
                            <a href="#" class="list-group-item">
                                <div class="media-box">
                                    <div class="pull-left">
                                        <em class="fa fa-envelope fa-2x text-warning"></em>
                                    </div>
                                    <div class="media-box-body clearfix">
                                        <p class="m0">New e-mails</p>
                                        <p class="m0 text-muted">
                                            <small>You have 10 new emails</small>
                                        </p>
                                    </div>
                                </div>
                            </a>
                            <!-- list item-->
                            <a href="#" class="list-group-item">
                                <div class="media-box">
                                    <div class="pull-left">
                                        <em class="fa fa-tasks fa-2x text-success"></em>
                                    </div>
                                    <div class="media-box-body clearfix">
                                        <p class="m0">Pending Tasks</p>
                                        <p class="m0 text-muted">
                                            <small>11 pending task</small>
                                        </p>
                                    </div>
                                </div>
                            </a>
                            <!-- last list item -->
                            <a href="#" class="list-group-item">
                                <small>More notifications</small>
                                <span class="label label-danger pull-right">14</span>
                            </a>
                        </div>
                        <!-- END list group-->
                    </li>
                </ul>
                <!-- END Dropdown menu-->
            </li>
            <!-- END Alert menu-->
            <!-- START Contacts button-->
            <li>
                <a href="#" data-toggle-state="offsidebar-open" data-no-persist="true">
                    <em class="icon-notebook"></em>
                </a>
            </li>
            <!-- END Contacts menu-->
        </ul>
        <!-- END Right Navbar-->
    </div>
    <!-- END Nav wrapper-->
    <!-- START Search form-->
    <form role="search" action="search.html" class="navbar-form">
        <div class="form-group has-feedback">
            <input type="text" placeholder="Type and hit enter ..." class="form-control" />
            <div data-search-dismiss="" class="fa fa-times form-control-feedback"></div>
        </div>
        <button type="submit" class="hidden btn btn-default">Submit</button>
    </form>
    <!-- END Search form-->
</nav>
<!-- END Top Navbar-->